common:
  msg_source: 1                                         
  send_packet_ros: false                               
  send_point_cloud_ros: true                           
  send_packet_proto: false                              
  send_point_cloud_proto: false                         
  pcap_path: /home/robosense/lidar.pcap 
lidar:
  - driver:
      # 192.168.1.21
      lidar_type: RSE1           
      frame_id: /rslidar
      group_address: 224.0.0.205
      host_address: 192.168.1.102           
      msop_port: 6666            
      difop_port: 6667            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: true        
    ros:
      ros_recv_packet_topic: /back/rslidar_packets    
      ros_send_packet_topic: /back/rslidar_packets    
      ros_send_point_cloud_topic: /back/rslidar_points      
    # proto:
    #   point_cloud_recv_port: 60021                     
    #   point_cloud_send_port: 60021                     
    #   msop_recv_port: 60022                       
    #   msop_send_port: 60022                       
    #   difop_recv_port: 60023                      
    #   difop_send_port: 60023       
    #   point_cloud_send_ip: 127.0.0.1                   
    #   packet_send_ip: 127.0.0.1    
  - driver:
    # driver:192.168.1.223
      lidar_type: RSE1           
      group_address: 224.0.0.205
      host_address: 192.168.1.102           

      frame_id: /rslidar           
      msop_port: 6676            
      difop_port: 6677            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: true        
    ros:
      ros_recv_packet_topic: /right/rslidar_packets    
      ros_send_packet_topic: /right/rslidar_packets    
      ros_send_point_cloud_topic: /right/rslidar_points      
    # proto:
    #   point_cloud_recv_port: 60024                     
    #   point_cloud_send_port: 60024                     
    #   msop_recv_port: 60025                       
    #   msop_send_port: 60025                       
    #   difop_recv_port: 60026                      
    #   difop_send_port: 60026       
    #   point_cloud_send_ip: 127.0.0.1                   
    #   packet_send_ip: 127.0.0.1   
  - driver:
    #  192.168.1.224

      lidar_type: RSE1           
      group_address: 224.0.0.205
      host_address: 192.168.1.102           

      frame_id: /rslidar           
      msop_port: 6686             
      difop_port: 6687            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: true        
    ros:
      ros_recv_packet_topic: /front/rslidar_packets    
      ros_send_packet_topic: /front/rslidar_packets    
      ros_send_point_cloud_topic: /front/rslidar_points      
    # proto:
    #   point_cloud_recv_port: 60027                     
    #   point_cloud_send_port: 60027                     
    #   msop_recv_port: 60028                       
    #   msop_send_port: 60028                       
    #   difop_recv_port: 60029                      
    #   difop_send_port: 60029       
    #   point_cloud_send_ip: 127.0.0.1                   
    #   packet_send_ip: 127.0.0.1    
  - driver:
    # driver:192.168.1.225
      lidar_type: RSE1           
      group_address: 224.0.0.205
      host_address: 192.168.1.102           

      frame_id: /rslidar           
      msop_port: 6696            
      difop_port: 6697            
      start_angle: 0              
      end_angle: 360               
      min_distance: 0.2            
      max_distance: 200            
      use_lidar_clock: true        
    ros:
      ros_recv_packet_topic: /left/rslidar_packets    
      ros_send_packet_topic: /left/rslidar_packets    
      ros_send_point_cloud_topic: /left/rslidar_points      
    # proto:
    #   point_cloud_recv_port: 60027                     
    #   point_cloud_send_port: 60027                     
    #   msop_recv_port: 60028                       
    #   msop_send_port: 60028                       
    #   difop_recv_port: 60029                      
    #   difop_send_port: 60029       
    #   point_cloud_send_ip: 127.0.0.1                   
    #   packet_send_ip: 127.0.0.1    
